# Generated by Django 2.0.2 on 2018-11-02 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('is_delete', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('condition_id', models.CharField(db_index=True, max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='条件唯一标识')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='条件名称')),
                ('condition_description', models.CharField(max_length=50, null=True, verbose_name='条件描述')),
                ('operator', models.CharField(max_length=50, verbose_name='条件对应的算子')),
                ('text_scope', models.CharField(default='1|-1', max_length=50, verbose_name='文本检测范围')),
                ('role_scope', models.SmallIntegerField(choices=[(0, '所有'), (1, '客服'), (2, '访客')], default=1, verbose_name='角色检测范围')),
                ('reference_content', models.CharField(max_length=256, null=True, verbose_name='参考语句')),
            ],
            options={
                'verbose_name_plural': '条件表',
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteid', models.CharField(max_length=256, verbose_name='企业id')),
                ('converid', models.CharField(max_length=256, verbose_name='会话id')),
                ('starttime', models.BigIntegerField(verbose_name='开始时间')),
                ('endtime', models.BigIntegerField(verbose_name='结束时间')),
                ('customerid', models.CharField(max_length=256, verbose_name='访客id')),
                ('firstsupplierid', models.CharField(max_length=256, verbose_name='客服id')),
                ('pointrules', models.CharField(max_length=256, null=True, verbose_name='命中的所有规则')),
                ('grade', models.IntegerField(null=True, verbose_name='总分')),
            ],
            options={
                'verbose_name_plural': '会话表',
            },
        ),
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteid', models.CharField(max_length=256, verbose_name='企业id')),
                ('conveid', models.CharField(max_length=256, verbose_name='会话id')),
                ('messageid', models.CharField(max_length=256, verbose_name='消息id')),
                ('createat', models.BigIntegerField(verbose_name='消息创建时间')),
                ('type', models.IntegerField(null=True, verbose_name='成员类型')),
                ('msgtype', models.IntegerField(null=True, verbose_name='消息类型')),
                ('message', models.CharField(max_length=256, null=True, verbose_name='消息内容')),
            ],
            options={
                'verbose_name_plural': '会话消息表',
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('is_delete', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('operation_id', models.CharField(db_index=True, max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='算子唯一标识')),
                ('operator_type', models.SmallIntegerField(choices=[(1, '说话时间间隔'), (2, '关键字'), (3, '是否是疑问句'), (4, '相似度分数'), (5, '积极类别的概率')], default=3, verbose_name='算子类型')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='算子名称')),
            ],
            options={
                'verbose_name_plural': '算子表',
            },
        ),
        migrations.CreateModel(
            name='QualityRule',
            fields=[
                ('is_delete', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('rule_id', models.CharField(db_index=True, max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='库表唯一标识')),
                ('site_id', models.CharField(max_length=50, verbose_name='企业唯一标识')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='规则名称')),
                ('rule_type', models.IntegerField(choices=[(1, '服务规范'), (2, '舆情监控'), (3, '业务类'), (4, '其他类')], default=1, verbose_name='规则类别')),
                ('rule_description', models.CharField(max_length=256, null=True, verbose_name='规则描述')),
                ('mood_expression', models.SmallIntegerField(default=1, verbose_name='正向负向')),
                ('condition', models.CharField(max_length=50, verbose_name='规则对应的条件')),
                ('grade', models.IntegerField(verbose_name='分数设置')),
                ('is_template', models.SmallIntegerField(default=0, verbose_name='是否是模板')),
            ],
            options={
                'verbose_name_plural': '规则表',
            },
        ),
        migrations.CreateModel(
            name='RulePoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conveid', models.CharField(max_length=256, null=True, verbose_name='会话id')),
                ('messageid', models.CharField(max_length=256, null=True, verbose_name='消息id')),
                ('ruleid', models.CharField(max_length=256, null=True, verbose_name='规则id')),
            ],
            options={
                'verbose_name_plural': '分析命中规则表',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('is_delete', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('task_id', models.CharField(db_index=True, max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='任务唯一标识')),
                ('site_id', models.CharField(max_length=50, verbose_name='站点ID')),
                ('name', models.CharField(max_length=50, verbose_name='任务名')),
                ('start_time', models.CharField(max_length=50, verbose_name='开始时间')),
                ('end_time', models.CharField(max_length=50, verbose_name='结束时间')),
            ],
            options={
                'verbose_name_plural': '质检任务表',
            },
        ),
    ]
